# Generated by Django 2.1.1 on 2018-11-15 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_desc', models.CharField(max_length=15)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2018, 11, 15, 19, 10, 28, 194162))),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
            ],
        ),
    ]
